name: CD
on:
  push:
    branches: [ prod ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  build-app:
    - name: Install dependencies
      run: yarn --cwd app
    - name: Build app
      run: yarn --cwd app build
    - name: Build Docker image
      run: yarn --cwd app docker-build
    - name: Publish to Registry
      run: docker push stefangeneralao/badminton_app

  build-api:
    - name: Install dependencies
      run: yarn --cwd server
    - name: Build server
      run: yarn --cwd server build
    - name: Build Docker image
      run: yarn --cwd server docker-build
    - name: Publish to Registry
      run: docker push stefangeneralao/badminton_api
