name: CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Bundle App
      run: |
        yarn --cwd app
        yarn --cwd app build
        yarn --cwd app docker-build
    - name: Publish to Registry
      run: docker push stefangeneralao/badminton_app
